<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-06-06T17:51:54 IST" name="Suite" finished-at="2024-06-06T17:52:20 IST" duration-ms="25592">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationsTest.loginErrorValidations()[pri:0, instance:FaisalAhmed.tests.ErrorValidationsTest@b86de0d]" name="loginErrorValidations" class="FaisalAhmed.tests.ErrorValidationsTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:FaisalAhmed.tests.SubmitOrderTest@49c90a9c]" name="submitOrder" class="FaisalAhmed.tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2024-06-06T17:51:54 IST" name="Error Validations Test" finished-at="2024-06-06T17:52:20 IST" duration-ms="25592">
      <class name="FaisalAhmed.tests.ErrorValidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:FaisalAhmed.tests.ErrorValidationsTest@b86de0d]" started-at="2024-06-06T17:51:54 IST" name="launchApplication" finished-at="2024-06-06T17:52:05 IST" duration-ms="10525" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidations()[pri:0, instance:FaisalAhmed.tests.ErrorValidationsTest@b86de0d]" started-at="2024-06-06T17:52:05 IST" name="loginErrorValidations" finished-at="2024-06-06T17:52:10 IST" duration-ms="5330" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login Successfully] but found [Incorrect email or password]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login Successfully] but found [Incorrect email or password]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at FaisalAhmed.tests.ErrorValidationsTest.loginErrorValidations(ErrorValidationsTest.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidations -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:FaisalAhmed.tests.ErrorValidationsTest@b86de0d]" started-at="2024-06-06T17:52:10 IST" name="tearDown" finished-at="2024-06-06T17:52:11 IST" duration-ms="401" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:FaisalAhmed.tests.ErrorValidationsTest@b86de0d]" started-at="2024-06-06T17:52:11 IST" name="launchApplication" finished-at="2024-06-06T17:52:16 IST" duration-ms="5049" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productErrorValidations()[pri:0, instance:FaisalAhmed.tests.ErrorValidationsTest@b86de0d]" started-at="2024-06-06T17:52:16 IST" name="productErrorValidations" finished-at="2024-06-06T17:52:19 IST" duration-ms="3219" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidations -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:FaisalAhmed.tests.ErrorValidationsTest@b86de0d]" started-at="2024-06-06T17:52:19 IST" name="tearDown" finished-at="2024-06-06T17:52:20 IST" duration-ms="454" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- FaisalAhmed.tests.ErrorValidationsTest -->
    </test> <!-- Error Validations Test -->
  </suite> <!-- Suite -->
</testng-results>
